# Netlify Configuration for Café com Vendas
# This file configures the build and deployment settings for the site

[build]
  # Build command - generates tokens, builds CSS/JS, and runs Eleventy
  command = "npm run build"
  
  # Output directory for the built site
  publish = "_site"
  
  # Functions directory
  functions = "netlify/functions"
  
  # Environment configuration
  [build.environment]
    NODE_VERSION = "22.17.1"
    NODE_OPTIONS = "--max-old-space-size=6144"  # 6GB for production builds
    SECRETS_SCAN_OMIT_KEYS = "VITE_FORMSPREE_FORM_ID,VITE_STRIPE_PUBLIC_KEY,VITE_GTM_CONTAINER_ID"

# Build processing - Vite handles all optimization, keep only essential settings
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Development settings - 2025 best practice: use Netlify dev for full-stack development
[dev]
  command = "eleventy --serve --watch --config=.eleventy.ts"
  targetPort = 8080
  publish = "_site"
  functions = "netlify/functions"

# Function-specific settings
[functions]
  node_bundler = "esbuild"

# URL redirects and rewrites
[[redirects]]
  # Redirect to thank-you page after successful payment
  from = "/payment-success"
  to = "/obrigado"
  status = 302

[[redirects]]
  # Redirect old URLs if needed
  from = "/thank-you"
  to = "/obrigado"
  status = 301

# GTM Server-side Preview Mode Support Redirects
[[redirects]]
  # Transparent proxy for Server GTM collect endpoint (alternative route)
  from = "/gtm/g/collect"
  to = "/.netlify/functions/gtm-proxy"
  status = 200
  force = true

[[redirects]]
  # Transparent proxy for Server GTM measurement protocol (alternative route)
  from = "/gtm/mp/collect"
  to = "/.netlify/functions/gtm-proxy"
  status = 200
  force = true

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy - COMPLETE Stripe requirements from official documentation
    # Based on https://docs.stripe.com/security/guide#content-security-policy
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://gtm.jucanamaximiliano.com.br https://js.stripe.com https://*.js.stripe.com https://checkout.stripe.com https://connect-js.stripe.com https://m.stripe.network https://www.youtube.com https://s.ytimg.com https://maps.googleapis.com; style-src 'self' 'unsafe-inline' data: https://fonts.googleapis.com https://*.stripe.com https://www.googletagmanager.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://res.cloudinary.com https://*.stripe.com https://www.googletagmanager.com https://gtm.jucanamaximiliano.com.br https://fonts.gstatic.com https://i.ytimg.com https://img.youtube.com; connect-src 'self' https://api.stripe.com https://checkout.stripe.com https://formspree.io https://connect.mailerlite.com https://*.google-analytics.com https://*.analytics.google.com https://www.googletagmanager.com https://gtm.jucanamaximiliano.com.br https://*.g.doubleclick.net https://www.youtube.com https://maps.googleapis.com; frame-src https://js.stripe.com https://*.js.stripe.com https://hooks.stripe.com https://checkout.stripe.com https://connect-js.stripe.com https://www.youtube.com https://www.youtube-nocookie.com https://gtm.jucanamaximiliano.com.br; object-src 'none'; base-uri 'self'; form-action 'self' https://formspree.io"
    
    # Modern security headers (2025 standards)
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    
    # HSTS with preload for enhanced security
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    
    # Performance headers
    X-DNS-Prefetch-Control = "on"

# Optimized asset caching - 2025 best practices
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"
    X-Content-Type-Options = "nosniff"

# Font files with long-term caching
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"
    Content-Type = "font/woff2"

# Headers for API endpoints
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Stripe-Signature"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# Environment-specific settings
[context.production]
  command = "npm ci --include=dev && npm run build"
  
  [context.production.environment]
    NODE_ENV = "production"
    ELEVENTY_ENV = "production"

[context.deploy-preview]
  command = "npm run build"
  
  [context.deploy-preview.environment]
    NODE_ENV = "development"
    ELEVENTY_ENV = "development"
    NODE_OPTIONS = "--max-old-space-size=2048"  # 2GB for faster previews

[context.branch-deploy]
  command = "npm run build"
  
  [context.branch-deploy.environment]
    NODE_ENV = "development"
    ELEVENTY_ENV = "development"
    NODE_OPTIONS = "--max-old-space-size=2048"  # 2GB for branch deploys

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs]
    output_path = "reports/lighthouse.html"
    
    [plugins.inputs.audits]
      performance = 90
      accessibility = 95
      best-practices = 90
      seo = 95

# Form processing (for Formspree backup)
[forms]
  spam_action = "block"
  honeypot_field = "_gotcha"